<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="16889" started-at="2018-08-21T10:18:15Z" finished-at="2018-08-21T10:18:32Z">
    <groups>
    </groups>
    <test name="API Test" duration-ms="16889" started-at="2018-08-21T10:18:15Z" finished-at="2018-08-21T10:18:32Z">
      <class name="com.APBCBS.api.TestCases.VerifyA006Response">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="setUp" is-config="true" duration-ms="2292" started-at="2018-08-21T15:48:07Z" finished-at="2018-08-21T15:48:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="configure()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="configure" is-config="true" duration-ms="5265" started-at="2018-08-21T15:48:10Z" depends-on-methods="com.APBCBS.api.Setup.TestSetup.setUp" finished-at="2018-08-21T15:48:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configure -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="beforeClass" is-config="true" duration-ms="7" started-at="2018-08-21T15:48:15Z" finished-at="2018-08-21T15:48:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-08-21T15:48:15Z" finished-at="2018-08-21T15:48:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(java.util.Hashtable) throws javax.xml.bind.JAXBException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyA006Response_0(java.util.Hashtable)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="verifyA006Response_0" duration-ms="12250" started-at="2018-08-21T15:48:15Z" data-provider="dp" finished-at="2018-08-21T15:48:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{toCustomerSegment=, EarmarkType_006=3, UserId=SYSTELLER, HoldAmount=1, endpoint=/fcrjappinterface, fromCustomerSegment=, HoldNumber=1, fromAccount=1000002054, SessionTicket=, ExternalBatchNumber=, Narrative=test1600, toCustNationalIdentificationCode=, ExpiryDate=20221201, PrimaryPassword=, TransactionBranch=9999, toAccount=8000965856, BankCode=753, ExternalSystemAuditTrailNumber=, ExternalReferenceNo=CBSAPI0002730052018, Channel=API, expectedErrorCode=0, fromCustNationalIdentificationCode=, OverridenWarnings=, ServiceCode=A006, ValueDateText=, UserReferenceNumber=, SupUserId=, expectedReplyText=Invalid input details, TxnAction=a, ToProductCode=, sOriginalReferenceNo=, PostingDateText=, LocalDateTimeText=, ProductCode=}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyA006Response_0 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="afterMethod" is-config="true" duration-ms="1576" started-at="2018-08-21T15:48:27Z" finished-at="2018-08-21T15:48:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-21T15:48:29Z" finished-at="2018-08-21T15:48:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(java.util.Hashtable) throws javax.xml.bind.JAXBException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="verifyA006Response_0(java.util.Hashtable)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="verifyA006Response_0" duration-ms="978" started-at="2018-08-21T15:48:29Z" data-provider="dp" finished-at="2018-08-21T15:48:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{toCustomerSegment=, EarmarkType_006=3, UserId=SYSTELLER, HoldAmount=1, endpoint=/fcrjappinterface, fromCustomerSegment=, HoldNumber=1, fromAccount=1000002054, SessionTicket=, ExternalBatchNumber=, Narrative=test1600, toCustNationalIdentificationCode=, ExpiryDate=20221201, PrimaryPassword=, TransactionBranch=9999, toAccount=8000965856, BankCode=753, ExternalSystemAuditTrailNumber=, ExternalReferenceNo=CBSAPI0002730052018, Channel=API, expectedErrorCode=0, fromCustNationalIdentificationCode=, OverridenWarnings=, ServiceCode=A006, ValueDateText=, UserReferenceNumber=, SupUserId=, expectedReplyText=Invalid input details, TxnAction=d, ToProductCode=, sOriginalReferenceNo=, PostingDateText=, LocalDateTimeText=, ProductCode=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [8102]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [8102]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.APBCBS.api.ApiClasses.A006API.postRequestWithValidData(A006API.java:36)
	at com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(VerifyA006Response.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyA006Response_0 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="afterMethod" is-config="true" duration-ms="120" started-at="2018-08-21T15:48:30Z" finished-at="2018-08-21T15:48:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-08-21T15:48:30Z" finished-at="2018-08-21T15:48:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(java.util.Hashtable) throws javax.xml.bind.JAXBException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="verifyA006Response_0(java.util.Hashtable)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="verifyA006Response_0" duration-ms="865" started-at="2018-08-21T15:48:30Z" data-provider="dp" finished-at="2018-08-21T15:48:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{toCustomerSegment=, EarmarkType_006=3, UserId=SYSTELLER, HoldAmount=1, endpoint=/fcrjappinterface, fromCustomerSegment=, HoldNumber=1, fromAccount=1000002054, SessionTicket=, ExternalBatchNumber=, Narrative=test1600, toCustNationalIdentificationCode=, ExpiryDate=20221201, PrimaryPassword=, TransactionBranch=9999, toAccount=8000965856, BankCode=753, ExternalSystemAuditTrailNumber=, ExternalReferenceNo=CBSAPI0002730052018, Channel=API, expectedErrorCode=0, fromCustNationalIdentificationCode=, OverridenWarnings=, ServiceCode=A006, ValueDateText=, UserReferenceNumber=, SupUserId=, expectedReplyText=Invalid input details, TxnAction=d, ToProductCode=, sOriginalReferenceNo=, PostingDateText=, LocalDateTimeText=, ProductCode=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [8102]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [8102]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.APBCBS.api.ApiClasses.A006API.postRequestWithValidData(A006API.java:36)
	at com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(VerifyA006Response.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyA006Response_0 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="afterMethod" is-config="true" duration-ms="88" started-at="2018-08-21T15:48:31Z" finished-at="2018-08-21T15:48:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-21T15:48:31Z" finished-at="2018-08-21T15:48:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(java.util.Hashtable) throws javax.xml.bind.JAXBException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyA006Response_0(java.util.Hashtable)[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="verifyA006Response_0" duration-ms="753" started-at="2018-08-21T15:48:31Z" data-provider="dp" finished-at="2018-08-21T15:48:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{toCustomerSegment=, EarmarkType_006=3, UserId=SYSTELLER, HoldAmount=1, endpoint=/fcrjappinterface, fromCustomerSegment=, HoldNumber=1, fromAccount=1000002054, SessionTicket=, ExternalBatchNumber=, Narrative=test1600, toCustNationalIdentificationCode=, ExpiryDate=20221201, PrimaryPassword=, TransactionBranch=9999, toAccount=8000965856, BankCode=753, ExternalSystemAuditTrailNumber=, ExternalReferenceNo=CBSAPI0002730052018, Channel=API, expectedErrorCode=0, fromCustNationalIdentificationCode=, OverridenWarnings=, ServiceCode=A006, ValueDateText=, UserReferenceNumber=, SupUserId=, expectedReplyText=Invalid input details, TxnAction=d, ToProductCode=, sOriginalReferenceNo=, PostingDateText=, LocalDateTimeText=, ProductCode=}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [0] but found [8102]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [0] but found [8102]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.APBCBS.api.ApiClasses.A006API.postRequestWithValidData(A006API.java:36)
	at com.APBCBS.api.TestCases.VerifyA006Response.verifyA006Response_0(VerifyA006Response.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyA006Response_0 -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="afterMethod" is-config="true" duration-ms="58" started-at="2018-08-21T15:48:32Z" finished-at="2018-08-21T15:48:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.APBCBS.api.TestCases.VerifyA006Response@75329a49]" name="afterSuite" is-config="true" duration-ms="0" started-at="2018-08-21T15:48:32Z" finished-at="2018-08-21T15:48:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.APBCBS.api.TestCases.VerifyA006Response -->
    </test> <!-- API Test -->
  </suite> <!-- Suite -->
</testng-results>
